### ISSUE TITLE
原生版本SDK商品详情界面空白

### ISSUE THREAD

**Issue by SunnyLy** [youzan/YouzanMobileSDK-Android#1]
Hi,运行原生版的Demo工程后，点击商品详情，界面空白 ；
运行基础版的Demo工程，点击商品详情，则有数据。
但根据您的md文档介绍所说：原生版的商品详情是需要登录，而基础版的是不需要登录就可以看到的。
如果这样的话，是不是搞反了。

**Comment by jackzzhll** [comment]
你好， md中的说明是：”基础版中现商品详情页面需登录可见, 原生版中无需登录即可浏览“，无误。
请检查下是否有设置token?
token分为两种，一种是无登录态的，一种是带第三方账号信息的。参考：https://www.youzanyun.com/docs/guide/appsdk/683。
访问商品详情页至少需要无登录态的token, 用以验明客户端的合法性。
