### ISSUE TITLE
导包之后编译项目报错

### ISSUE THREAD

**Issue by tpnet** [youzan/YouzanMobileSDK-Android#2]
就导包，一行代码都不加，编译项目，就报错,，，报错如图：

![错误](https://github.com/tpnet/BackFile/blob/master/youzan_error.png)

很紧急，求助

**Comment by tpnet** [comment]
已经解解决，需要exclude 谷歌的包：
```
implementation ('com.youzanyun.open.mobile:hybrid:5.3.5') {
        exclude group: 'com.google.android', module: 'android'
 }
```

**Comment by chengruilin** [comment]
`compile ('com.youzanyun.open.mobile:hybrid:5.3.5') {
        exclude group: 'com.google.android', module: 'android'
    }
`
查看组件的依赖发现有  com.google.android:android:2.2.1 ，需要把它exclude 调，否则会报问题找不到
