### ISSUE TITLE
YouzanBrowser 卡死 导致整个app中webview无法使用

### ISSUE THREAD

**Issue by YougaKing** [youzan/YouzanMobileSDK-Android#4]
![image](https://user-images.githubusercontent.com/16010591/37456499-85ab8b66-287a-11e8-80cd-18c0194e8c55.png)
点击有赞商品详情页面，快速关闭即可出现

**Comment by jackzzhll** [comment]
机型、sdk版本是多少？
这个问题，看起来跟YouzanBrowser没关系啊。

**Comment by YougaKing** [comment]
是你们其中一个版本的问题， 我升级就好了
