### ISSUE TITLE
引入的库总是和项目中重复

### ISSUE THREAD

**Issue by ArnoFrost** [youzan/YouzanMobileSDK-Android#6]
首先是v7包 然后是okhttp3 但是现在不知道该怎么去掉okhttp3的引入了 

> `    api 'com.youzanyun.open.mobile:x5sdk:6.4.9',{
        exclude group: 'com.android.support'
        exclude group: "com.squareup.okio", module: "okio"
        exclude group: "com.squareup.okhttp3"
        exclude group: 'com.google.code.gson'
    }`
我试着这样去写 是这样的吗

**Comment by EnternalRain** [comment]
看着没什么问题。
