### ISSUE TITLE
请问应该怎样把sdk分出来？

### ISSUE THREAD

**Issue by senRsl** [youzan/YouzanMobileSDK-Android#8]
比方说 

我只需要一个 店铺功能，或者只需要一个聊天功能，

或者 我的 代码里已经内置了 okhttp,或者 x5浏览器。

能不能使用分开的方式，如 阿里或者 腾讯的sdk， 什么样的功能加载 什么样的包，什么样的功能可以不去加载什么样的库。

按照 wiki的方式，我集成之后 有 7个包进来，如图

<img width="420" alt="2018-10-25 7 56 23" src="https://user-images.githubusercontent.com/4360383/47498765-cb26ad80-d890-11e8-9225-945ebf6adbbf.png">

本身我的项目只有5M，集成有赞SDK后发现直接变成了10M。

请问应该如何做些优化？

谢谢.

**Comment by EnternalRain** [comment]
目前暂时只支持x5内核的按情况加载（即：自身项目已经有集成x5内核的情况下，可以exclude掉x5official），im库后面会考虑按需加载。其他库都是必须的。

**Comment by EnternalRain** [comment]
后续支持

**Comment by jp1017** [comment]
> 可以exclude掉x5official）

请问如何书写的，module和group是个啥？麻烦了
